services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit-mq-management-1"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5000:5673"
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/mnesia/'
    networks:
      - backend
    restart: always

  rabbit-consumer:
    image: "docker-rabbitmq-consumer"
    build:
      context: .
      dockerfile: consumer.Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

volumes:
  rabbitmq_data:

networks:
  backend:
    driver: bridge
