# https://taskfile.dev

version: '3'

vars:
  EXENAMEP1: producer.exe
  EXENAMEP2: consumer.exe

tasks:
  build-producer:
    cmds:
      - go build -o ./producer/bin/{{.EXENAMEP1}} producer/main.go
    silent: true

  run-producer:
    deps: [build-producer]
    cmds:
      - ./producer/bin/{{.EXENAMEP1}}
    silent: true

  compose-up:
    cmds:
      - docker compose up -d # -d == silent compose

  compose-down:
    cmds:
      - docker compose down

  build-consumer:
    cmds:
      - go build -o ./consumer/bin/{{.EXENAMEP2}} consumer/main.go
    silent: true

  run-consumer:
    deps: [build-consumer]
    cmds:
      - ./consumer/bin/{{.EXENAMEP2}}
    silent: true

  build-consumer-dockerfile:
    cmds:
      - docker build -f consumer.Dockerfile --tag docker-rabbitmq-consumer .
