# http:
#   routers:
#     native-api:
#       rule: "Host(`localhost`) && PathPrefix(`/api`)"
#       service: native-api

#   services:
#     native-api:
#       loadBalancer:
#         servers:
#           - url: "http://host.docker.internal:8083/"
